version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-up-api
    ports:
      - "8080:8080"
    environment:
      - SERVER_ADDR=:8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=photoapi
      - DB_PASSWORD=secret
      - DB_NAME=photoapi
      - DB_SSLMODE=disable
      - REDIS_ADDR=redis:6379
      - AUTH_TOKEN_SECRET=local-dev-secret-key
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
    depends_on:
      - postgres
      - redis
      - localstack
    networks:
      - goup-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: photoapi
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: photoapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - goup-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U photoapi -d photoapi"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - goup-network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:latest
    container_name: goup-localstack
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - "4566:4566"
    volumes:
      - "./scripts/localstack-init:/docker-entrypoint-initaws.d"
    networks:
      - goup-network

networks:
  goup-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: