// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreatePhoto(ctx context.Context, arg CreatePhotoParams) (Photo, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePhoto(ctx context.Context, id uuid.UUID) error
	GetPhotoByID(ctx context.Context, id uuid.UUID) (Photo, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListUserPhotos(ctx context.Context, arg ListUserPhotosParams) ([]Photo, error)
	UpdatePhotoDetails(ctx context.Context, arg UpdatePhotoDetailsParams) (Photo, error)
}

var _ Querier = (*Queries)(nil)
