// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountPhotosByUserID(ctx context.Context, userID uuid.UUID) (int64, error)
	CreatePhoto(ctx context.Context, arg CreatePhotoParams) (Photo, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePhoto(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetPhotoByID(ctx context.Context, id uuid.UUID) (Photo, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUserName(ctx context.Context, username string) (User, error)
	ListPhotosByUserID(ctx context.Context, arg ListPhotosByUserIDParams) ([]Photo, error)
	UpdatePhoto(ctx context.Context, arg UpdatePhotoParams) (Photo, error)
	UpdatePhotoStorageInfo(ctx context.Context, arg UpdatePhotoStorageInfoParams) (Photo, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
